services:
  db:
    image: manikanta6565/py:db_image
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: manikanta6565/py:auth_image
    ports:
      - "6001:6001"
    networks:
      - mynetwork
    depends_on:
      - db

  book_service:
    image: manikanta6565/py:book_image
    ports:
      - "6002:6002"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow_service:
    image: manikanta6565/py:borrow_image
    ports:
      - "6003:6003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: manikanta6565/py:frontend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
