services:
  db:
    image: manikanta6565/py:db_image
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth:
    image: manikanta6565/py:auth_image
    ports:
      - "1313:1313"
    networks:
      - mynetwork
    depends_on:
      - db

  book:
    image: manikanta6565/py:book_image
    ports:
      - "1314:1314"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow:
    image: manikanta6565/py:borrow_image
    ports:
      - "1315:1315"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: manikanta6565/py:frontend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
